server:
  port: 8080

spring:
  application:
    name: BarCommerce

  datasource:
    url: jdbc:mariadb://localhost:3306/barcommerce
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  cache:
    type: redis
    redis:
      time-to-live: 60s
  redis:
    host: localhost
    port: 6379

  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

app:
  mesa:
    latitude: -23.550520
    longitude: -46.633308
  base-url: http://localhost:8080
  upload:
    dir: ./uploads/produtos
    allowed-types: image/jpeg,image/png,image/gif

# Configurações do JWT
jwt:
  secret: PjB1EU32+zohxnFX9FZQXA7hJDjBmJI6EoWqCbwLeG8=
  expiration: 86400000  # 1 dia em milissegundos
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG

mercadopago:
  access:
    token: TEST-241e5740-63a9-4bd1-a0a8-e3ff5c11cd60
  email:
    padrao: mauricioantonionetinho@gmail.com
servico:
  ml:
    url: http://localhost:5000